version: "3.8"
services:
  webserver:
    image: nginx:1-alpine
    ports:
      - "80:80"
    volumes:
      - "$PWD/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "$PWD/src:/usr/share/nginx/html"
  php:
    image: php:8.3-fpm-alpine
    ports:
      - "9000"
    volumes:
      - "$PWD/src:/var/www/html"
  database:
    image: postgres:16.2-alpine
    ports:
      - "5432"
    environment:
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_DB=${DATABASE_NAME}"