version: "3.8"
services:
  webserver:
    image: nginx:1-alpine
    ports:
      - "80:80"
    volumes:
      - "$PWD/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "$PWD:/usr/share/nginx/html"
  php:
    build: "docker/php"
    ports:
      - "9000"
    volumes:
      - "$PWD:/var/www/html"
    environment:
      - "XDEBUG_MODE=coverage"
  database:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_DB=${DATABASE_NAME}"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
volumes:
  database_data: